### ISSUE TITLE
Can not connect with the wallet to access 3ID

### ISSUE THREAD

**Issue by sonphambk** [LearnWeb3DAO/Ceramic#7]
Hi @all
Thank you for your work
I tried to implement like the tutorial but when I clicked on Connect Button. The error was occurred.
![image](https://user-images.githubusercontent.com/48971289/197372595-f50adad9-f483-4ea4-8a18-295012ab1e68.png)
How can we resolve this problem?
Thanks
@Sneh1999

**Comment by sonphambk** [comment]
@KacieAhmed @haardikk21

**Comment by sonphambk** [comment]
@AAYUSH-GUPTA-coder

**Comment by 0xStalin-eth** [comment]
@sonphambk I'm having the same issue, I did a thousand tests trying to figure out what's wrong.
I'm using the exact same package versions as the ones from this repo, and my best hint about this error is related to this post:
https://blog.ceramic.network/what-is-3id-connect/

Looks like the versions that were used when this repo was created are pointing to a deprecated URL, and that's why we are getting that 404 error

**Comment by 0xStalin-eth** [comment]
I've pushed my code to this repository, in case someone could take a look at it and verify the package versions I'm using
https://github.com/stalinMacias/ceramic-lesson-issues
@haardikk21

**Comment by GorniyGor** [comment]
@sonphambk @stalinMacias 
Maybe it will fix the problem
https://github.com/ceramicnetwork/js-ceramic/pull/2628
